
module.exports = Object.freeze({
    ERROR_OK: 0,
    ERROR_FAN_POWER_100: 100,
    ERROR_FAN_POWER_ORDER: 101,
    ERROR_FAN_TEMP_ORDER: 102,
    ERROR_TEMP_THRESHOLD_ORDER: 103,
    ERROR_VOLT_THRESHOLD_ORDER: 104,
    ERROR_EMPTY: 105,
    ERROR_IP: 106,
});